bin: Add check for nonstandard programs

diff --git a/home/bin/color-png-alpha b/home/bin/color-png-alpha
--- a/home/bin/color-png-alpha
+++ b/home/bin/color-png-alpha
@@ -31,6 +31,26 @@ done
 
 shift "$((OPTIND-1))"
 
+check_required_binaries() {
+    local BIN MISSING=()
+    for BIN; do
+        if ! type -t "$BIN" &>/dev/null; then
+            MISSING+=("$BIN")
+        fi
+    done
+    if [[ ${#MISSING[@]} -gt 0 ]]; then
+        printf 'Error: You are missing required programs:\n' >&2
+        for BIN in "${MISSING[@]}"; do
+            printf -- '- %s\n' "$BIN" >&2
+        done
+        exit 2
+    fi
+}
+
+check_required_binaries \
+    pngtopnm \
+    pnmtopng
+
 if [[ -n $1 ]]; then
     INFILE=$1
 fi
