bin: Use better method of executing wrapped programs
Don't modify PATH when executing wrapped programs; less, for instance,
can launch an editor or a shell.

diff --git a/home/bin/less b/home/bin/less
--- a/home/bin/less
+++ b/home/bin/less
@@ -3,15 +3,23 @@
 
 # colorized manpages
 
-# Remove self from path
-BINDIR=${0%/*}
-PATH=:$PATH:
-while [[ $PATH = *:$BINDIR:* ]]; do
-    PATH=${PATH//:$BINDIR:/:}
-done
-# Trim off ":" from the beginning and end.
-PATH=${PATH#:}
-PATH=${PATH%:}
+next_bin() (
+    # Find path to wrapped program
+    BINNAME=${0##*/}
+    while read -r BIN; do
+        if [[ ! $BIN -ef $0 ]]; then
+            printf '%s\n' \
+                "$BIN"
+            return 0
+        fi
+    done < <(type -aP -- "$BINNAME")
+    printf 'Wrapped program not found in PATH: %s\n' \
+        "$BINNAME" \
+        >&2
+    return 127
+)
+
+REALBIN=$(next_bin) || exit
 
 LESS_TERMCAP_mb=$'\e[05m' \
 LESS_TERMCAP_md=$'\e[01;38;5;38m' \
@@ -20,5 +28,5 @@ LESS_TERMCAP_so=$'\e[07;38;5;154m' \
 LESS_TERMCAP_se=$'\e[0m' \
 LESS_TERMCAP_us=$'\e[04;01;38;5;165m' \
 LESS_TERMCAP_ue=$'\e[0m' \
-exec less \
+exec "$REALBIN" \
     "$@"
diff --git a/qemu/bin/qemu-nbd b/qemu/bin/qemu-nbd
--- a/qemu/bin/qemu-nbd
+++ b/qemu/bin/qemu-nbd
@@ -1,8 +1,6 @@
 #!/bin/bash
 # vi: et sts=4 sw=4 ts=4
 
-_MYBINDIR=$(dirname -- "$0")
-
 ask_yn() (
     PROMPT=$1
     DEFAULT=$2
@@ -45,27 +43,31 @@ if [[ -t 1 ]]; then
     fi
 fi
 
-# Alter path so we don't start ourselves again
-PATH=:$PATH:
-while [[ $PATH = *:$_MYBINDIR:* ]]; do
-    PATH=${PATH//:$_MYBINDIR:/:}
-done
-PATH=${PATH#:}
-PATH=${PATH%:}
+next_bin() (
+    # Find path to wrapped program
+    BINNAME=${0##*/}
+    while read -r BIN; do
+        if [[ ! $BIN -ef $0 ]]; then
+            printf '%s\n' \
+                "$BIN"
+            return 0
+        fi
+    done < <(type -aP -- "$BINNAME")
+    printf 'Wrapped program not found in PATH: %s\n' \
+        "$BINNAME" \
+        >&2
+    return 127
+)
 
-if [[ $(which -- qemu-nbd 2>/dev/null) = "$0" ]]; then
-    # Can't happen
-    echo "$0: Bug! Refusing to infinitely start self" >&2
-    exit 2
-fi
+REALBIN=$(next_bin) || exit
 
 if [[ ${#EXTRA_ARGS[@]} -gt 0 ]]; then
     # Show you what I'm doing
     set -x
-    exec qemu-nbd \
+    exec "$REALBIN" \
         "${EXTRA_ARGS[@]}" \
         "$@"
 else
-    exec qemu-nbd \
+    exec "$REALBIN" \
         "$@"
 fi
